### PR TITLE
chore: bump cardano service deps

### PR DESCRIPTION
**Pull request by rhyslbw**
# Description
Updates:
- cabal@3.6.2.0
- cardano-node@1.35.4
- cardano-db-sync@13.1.0.0

### CODE REVIEW

**Comment by 0xtrossets** [comment]
Looks like build isn't working. Tried locally and seeing the same issue.

**Comment by 0xtrossets** [comment]
@rhyslbw Might need a cabal version bump also?

**Comment by 0xtrossets** [comment]
@rhyslbw how soon do you estimate the next release with this included?

**Comment by rhyslbw** [comment]
We first need https://github.com/input-output-hk/cardano-rosetta/pull/528 to resolve a bug introduced here @0xtrossets, but it's getting close now.

**Pull request merged**
