### PR TITLE
bors config

### PR DESCRIPTION
**Pull request by disassembler**
# Description

Adds bors.toml so can trigger CI retests easier

# Proposed Solution

_**Optional** Explain how does this PR solves the problem stated in [Description](#Description). You can also enumerate different alternatives considered while approaching this task._

# Important Changes Introduced

_**Optional** Notice Reviewers about changes that were introduced while developing this task_

# Testing

_**Optional** Leave some recommendations should be useful while reviewers are testing this PR_

### CODE REVIEW

**Comment by disassembler** [comment]
bors try

**Comment by disassembler** [comment]
bors try-

**Comment by disassembler** [comment]
bprs try

**Comment by disassembler** [comment]
bors try

**Comment by disassembler** [comment]
bors try-

**Comment by disassembler** [comment]
bors try

**Comment by rhyslbw** [comment]
@disassembler is this working? The last test timed out

**Pull request merged**
