### PR TITLE
Chore: cardano-db-sync@10.0.0 / cardano-node@1.27.0

### PR DESCRIPTION
**Pull request by rhyslbw**
# Description
Minimum compatibility update

# Proposed Solution
n/a

# Important Changes Introduced
n/a

# Testing
~~Automated. CI results should be ignored until snapshot has been submitted.~~

# Todo
- [x] Update DB snapshot
- [x] Convert test cases targeting `launchpad` to `mainnet`

### CODE REVIEW

**Comment by rhyslbw** [comment]
@toaspzoo I've pushed this branch before being able to verify the changes, but it will allow you to also get the new version syncing. Changes are untested and the CI results should be ignored until this has been completed: https://github.com/input-output-hk/cardano-rosetta/tree/master/cardano-rosetta-server#generating-test-data for more details.

**Review by toaspzoo — APPROVED** [review]
LGTM
Successfully performed `mainnet` synchronization using `cardano-node 1.27.0` and `cardano-db-sync 10.0.0`

**Comment by rhyslbw** [comment]
Thanks for the update @toaspzoo , but there's a few more items to cover before this is ready. Documentation for the `check` tests is here: https://github.com/input-output-hk/cardano-rosetta/tree/master/test/check. @james-iohk or I will be able to assist with this if you get stuck or have questions.

**Review by rhyslbw — COMMENTED** [review]
To verify the account balance and transaction assertions I've generated two golden test files (attached) using the [@cardano-js-sdk/golden-test-generator](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/golden-test-generator). This tool syncs the chain to capture block information and calculate the account balances at the provided block heights. I've found a couple of discrepancies with asset balances, which have been highlighted inline, so we need to reconcile this before proceeding. 

@jvieiro 
Given the database used in the tests here is a derived dataset using a query to produce a sudo snapshot, can you please run the tests against a live instance to compare the results?

[golden-test-files.zip](https://github.com/input-output-hk/cardano-rosetta/files/6830690/golden-test-files.zip)

**Comment by jvieiro** [comment]
> To verify the account balance and transaction assertions I've generated two golden test files (attached) using the [@cardano-js-sdk/golden-test-generator](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/golden-test-generator). This tool syncs the chain to capture block information and calculate the account balances at the provided block heights. I've found a couple of discrepancies with asset balances, which have been highlighted inline, so we need to reconcile this before proceeding.
> 
> @jvieiro
> Given the database used in the tests here is a derived dataset using a query to produce a sudo snapshot, can you please run the tests against a live instance to compare the results?
> 
> [golden-test-files.zip](https://github.com/input-output-hk/cardano-rosetta/files/6830690/golden-test-files.zip)

@rhyslbw I ran the query being used in rosetta in a live instance of mainnet. The values I've received are the same as the expected in the test suite. Also, I've noticed that the discrepancies start from the 4th decimal reading it from right to left.
I let you the query I used:
  ```
WITH utxo AS (
	SELECT
	  tx_out.value as value,
	  tx_out_tx.hash as "txHash",
	  tx_out.index as index,
	  tx_out.id as tx_out_id
	FROM tx_out
	LEFT JOIN tx_in ON 
	  tx_out.tx_id = tx_in.tx_out_id AND 
	  tx_out.index::smallint = tx_in.tx_out_index::smallint 
	LEFT JOIN tx as tx_in_tx ON 
	  tx_in_tx.id = tx_in.tx_in_id AND
	  tx_in_tx.block_id <= (select id from block where block_no = 5455974)
	JOIN tx AS tx_out_tx ON
	  tx_out_tx.id = tx_out.tx_id AND
	  tx_out_tx.block_id <= (select id from block where block_no = 5455974)
	WHERE 
	  tx_out.address = 'addr1qx5d5d8aqn0970nl3km63za5q87fwh2alm79zwuxvh6rh9lg96s8las2lwer5psc7yr59kmafzkz2l5jz4dyxghs7pvqj24sft' AND
	  tx_in_tx.id IS NULL
)
 SELECT
      ma_tx_out.name as "name",
      ma_tx_out.policy as "policy",
      SUM(ma_tx_out.quantity) as value
  FROM utxo
      LEFT JOIN ma_tx_out 
      ON ma_tx_out.tx_out_id = utxo.tx_out_id 
  WHERE ma_tx_out.policy IS NOT NULL;
```

**Comment by jvieiro** [comment]
> > To verify the account balance and transaction assertions I've generated two golden test files (attached) using the [@cardano-js-sdk/golden-test-generator](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/golden-test-generator). This tool syncs the chain to capture block information and calculate the account balances at the provided block heights. I've found a couple of discrepancies with asset balances, which have been highlighted inline, so we need to reconcile this before proceeding.
> > @jvieiro
> > Given the database used in the tests here is a derived dataset using a query to produce a sudo snapshot, can you please run the tests against a live instance to compare the results?
> > [golden-test-files.zip](https://github.com/input-output-hk/cardano-rosetta/files/6830690/golden-test-files.zip)
> 
> @rhyslbw I ran the query being used in rosetta in a live instance of mainnet. The values I've received are the same as the expected in the test suite.
> I let you the query I used:
> 
> ```
> WITH utxo AS (
>   SELECT
>     tx_out.value as value,
>     tx_out_tx.hash as "txHash",
>     tx_out.index as index,
>     tx_out.id as tx_out_id
>   FROM tx_out
>   LEFT JOIN tx_in ON 
>     tx_out.tx_id = tx_in.tx_out_id AND 
>     tx_out.index::smallint = tx_in.tx_out_index::smallint 
>   LEFT JOIN tx as tx_in_tx ON 
>     tx_in_tx.id = tx_in.tx_in_id AND
>     tx_in_tx.block_id <= (select id from block where block_no = 5455974)
>   JOIN tx AS tx_out_tx ON
>     tx_out_tx.id = tx_out.tx_id AND
>     tx_out_tx.block_id <= (select id from block where block_no = 5455974)
>   WHERE 
>     tx_out.address = 'addr1qx5d5d8aqn0970nl3km63za5q87fwh2alm79zwuxvh6rh9lg96s8las2lwer5psc7yr59kmafzkz2l5jz4dyxghs7pvqj24sft' AND
>     tx_in_tx.id IS NULL
> )
> SELECT
>     ma_tx_out.name as "name",
>     ma_tx_out.policy as "policy",
>     SUM(ma_tx_out.quantity) as value
> FROM utxo
>     LEFT JOIN ma_tx_out 
>     ON ma_tx_out.tx_out_id = utxo.tx_out_id 
> WHERE ma_tx_out.policy IS NOT NULL
> GROUP  BY ma_tx_out.name, ma_tx_out.policy
> ORDER BY ma_tx_out.policy, ma_tx_out.name;
> ```

Also, I've noticed that the discrepancies start from the 4th number reading it from right to left. Maybe there could be a rounding issue.

**Comment by AlanVerbner** [comment]
> > > To verify the account balance and transaction assertions I've generated two golden test files (attached) using the [@cardano-js-sdk/golden-test-generator](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/golden-test-generator). This tool syncs the chain to capture block information and calculate the account balances at the provided block heights. I've found a couple of discrepancies with asset balances, which have been highlighted inline, so we need to reconcile this before proceeding.
> > > @jvieiro
> > > Given the database used in the tests here is a derived dataset using a query to produce a sudo snapshot, can you please run the tests against a live instance to compare the results?
> > > [golden-test-files.zip](https://github.com/input-output-hk/cardano-rosetta/files/6830690/golden-test-files.zip)
> > 
> > 
> > @rhyslbw I ran the query being used in rosetta in a live instance of mainnet. The values I've received are the same as the expected in the test suite.
> > I let you the query I used:
> > ```
> > WITH utxo AS (
> >   SELECT
> >     tx_out.value as value,
> >     tx_out_tx.hash as "txHash",
> >     tx_out.index as index,
> >     tx_out.id as tx_out_id
> >   FROM tx_out
> >   LEFT JOIN tx_in ON 
> >     tx_out.tx_id = tx_in.tx_out_id AND 
> >     tx_out.index::smallint = tx_in.tx_out_index::smallint 
> >   LEFT JOIN tx as tx_in_tx ON 
> >     tx_in_tx.id = tx_in.tx_in_id AND
> >     tx_in_tx.block_id <= (select id from block where block_no = 5455974)
> >   JOIN tx AS tx_out_tx ON
> >     tx_out_tx.id = tx_out.tx_id AND
> >     tx_out_tx.block_id <= (select id from block where block_no = 5455974)
> >   WHERE 
> >     tx_out.address = 'addr1qx5d5d8aqn0970nl3km63za5q87fwh2alm79zwuxvh6rh9lg96s8las2lwer5psc7yr59kmafzkz2l5jz4dyxghs7pvqj24sft' AND
> >     tx_in_tx.id IS NULL
> > )
> > SELECT
> >     ma_tx_out.name as "name",
> >     ma_tx_out.policy as "policy",
> >     SUM(ma_tx_out.quantity) as value
> > FROM utxo
> >     LEFT JOIN ma_tx_out 
> >     ON ma_tx_out.tx_out_id = utxo.tx_out_id 
> > WHERE ma_tx_out.policy IS NOT NULL
> > GROUP  BY ma_tx_out.name, ma_tx_out.policy
> > ORDER BY ma_tx_out.policy, ma_tx_out.name;
> > ```
> 
> Also, I've noticed that the discrepancies start from the 4th number reading it from right to left. Maybe there is a rounding issue.

@rhyslbw actually take a look at this https://cardanoscan.io/address/01a8da34fd04de5f3e7f8db7a88bb401fc975d5dfefc513b8665f43b97e82ea07ff60afbb23a0618f10742db7d48ac257e92155a4322f0f058

**Comment by rhyslbw** [comment]
Thanks for the investigation @jvieiro and @AlanVerbner.

> Also, I've noticed that the discrepancies start from the 4th number reading it from right to left. Maybe there is a rounding issue.

Now that you point this out it's obviously a mishandling of large integers. I'll fix (and add larger numbers to my test scenarios :smile:  ) and re-run.

**Pull request merged**
